### ISSUE TITLE
Error: incompatible encodings: ASCII-8BIT and UTF-8 while creating account

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#128]
_Let's time box it and move on if it's not easily reproducible_

Seen with 0.15.5 Docker image, when creating an account (default fields values). Is it reproducible?

```
Nov 20, 2017 6:32:55 AM org.apache.catalina.core.ApplicationContext log
INFO: Encoding::CompatibilityError incompatible encodings: ASCII-8BIT and UTF-8. org/jruby/RubyString.java:2630:in `concat'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.8/lib/active_support/core_ext/string/output_safety.rb:185:in `concat'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/buffers.rb:12:in `<<'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/kaui-0.15.5/app/views/kaui/layouts/kaui_application.html.erb:15:in `_gems_gems_kaui________app_views_kaui_layouts_kaui_application_html_erb___2057779829_8570'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/lib/jruby-stdlib-1.7.24.jar!/META-INF/jruby.home/lib/ruby/2.0/benchmark.rb:296:in `realtime'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
/var/lib/tomcat7/webapps/ROOT/WEB-INF/gems/gems/kaui-0.15.5/app/controllers/kaui/accounts_controller.rb:69:in `create'
```

**Comment by pierre** [comment]
Unable to reproduce.

**Comment by pierre** [comment]
See https://github.com/killbill/killbill/issues/1025.
