### ISSUE TITLE
Regression with 0.9.0 and Kill Bill 0.18.5?

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#146]
_Let's time box it and move on if it's not easily reproducible_

Investigate a possible regression reported on the mailing-list [here](https://groups.google.com/forum/#!msg/killbilling-users/Shq0upWPZLo/EdnlTZr3AgAJ) if it's reproducible with the docker-compose setup he posted (if not, we will need more information from the user).

**Comment by pierre** [comment]
Error seen on 0.19.4 which could be related:

```
2018-03-02T15:58:02,024+0000 lvl='WARN', log='EntitySqlDaoWrapperInvocationHandler', th='catalina-exec-8', xff='', rId='302592e7-5048-43e4-83e1-571969ccc3be', aRId='4068', tRId='9', Error during transaction for sql entity interface org.killbill.billing.subscription.engine.dao.SubscriptionEventSqlDao and method getByAccountRecordId
2018-03-02T15:58:02,026+0000 lvl='WARN', log='LoggingResponse', th='catalina-exec-8', xff='', rId='302592e7-5048-43e4-83e1-571969ccc3be', aRId='4068', tRId='9', Bad request
java.lang.IllegalArgumentException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.killbill.commons.jdbi.mapper.LowerToCamelBeanMapper.map(LowerToCamelBeanMapper.java:270)
	at org.skife.jdbi.v2.RegisteredMapper.map(RegisteredMapper.java:37)
	at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
	at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:43)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1342)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.list(Query.java:82)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:255)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:48)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:45)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:180)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:93)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$f2f2a44f.getByAccountRecordId(<generated>)
	at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$2.execute(EntitySqlDaoWrapperInvocationHandler.java:211)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeRaw(EntitySqlDaoWrapperInvocationHandler.java:208)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invokeSafely(EntitySqlDaoWrapperInvocationHandler.java:203)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.access$000(EntitySqlDaoWrapperInvocationHandler.java:84)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler$1.execute(EntitySqlDaoWrapperInvocationHandler.java:124)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:33)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoWrapperInvocationHandler.invoke(EntitySqlDaoWrapperInvocationHandler.java:121)
	at com.sun.proxy.$Proxy244.getByAccountRecordId(Unknown Source)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$27.inTransaction(DefaultSubscriptionDao.java:802)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao$27.inTransaction(DefaultSubscriptionDao.java:799)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:71)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$JdbiTransaction.inTransaction(EntitySqlDaoTransactionalJdbiWrapper.java:58)
	at org.skife.jdbi.v2.sqlobject.InTransactionWithIsolationLevelHandler$1.inTransaction(InTransactionWithIsolationLevelHandler.java:39)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184)
	at org.skife.jdbi.v2.tweak.transactions.DelegatingTransactionHandler.inTransaction(DelegatingTransactionHandler.java:82)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:60)
	at org.killbill.commons.jdbi.transaction.RestartTransactionRunner.inTransaction(RestartTransactionRunner.java:86)
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:340)
	at org.skife.jdbi.v2.sqlobject.InTransactionWithIsolationLevelHandler.invoke(InTransactionWithIsolationLevelHandler.java:34)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:180)
	at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:93)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper$InitialEntitySqlDao$$EnhancerByCGLIB$$c1ea5573.inTransaction(<generated>)
	at org.killbill.billing.util.entity.dao.EntitySqlDaoTransactionalJdbiWrapper.execute(EntitySqlDaoTransactionalJdbiWrapper.java:87)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getEventsForAccountId(DefaultSubscriptionDao.java:799)
	at org.killbill.billing.subscription.engine.dao.DefaultSubscriptionDao.getSubscriptionsForAccount(DefaultSubscriptionDao.java:417)
	at org.killbill.billing.subscription.api.svcs.DefaultSubscriptionInternalApi.getSubscriptionsForAccount(DefaultSubscriptionInternalApi.java:501)
	at org.killbill.billing.entitlement.engine.core.EventsStreamBuilder.buildForAccount(EventsStreamBuilder.java:126)
	at org.killbill.billing.entitlement.api.svcs.DefaultEntitlementApiBase.getAllEntitlementsForAccount(DefaultEntitlementApiBase.java:117)
	at org.killbill.billing.entitlement.api.DefaultSubscriptionApi.getSubscriptionBundlesForAccount(DefaultSubscriptionApi.java:456)
	at org.killbill.billing.entitlement.api.DefaultSubscriptionApi.getSubscriptionBundlesForAccountId(DefaultSubscriptionApi.java:215)
```

**Comment by wwjbatista** [comment]
Since `subscription option` for kaui 0.9.0 uses ` /1.0/kb/accounts/{accountId}/allCustomFields` endpoint to retrieve account custom fields, the minimum version of killbill must be `0.18.13` (this is the version in wich it is available for the first time).

**Comment by pierre** [comment]
Good catch @wwjbatista!
